apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-test
  namespace: todoapp
spec:
  action: pod-failure
  mode: one
  selector:
    namespaces:
      - todoapp
    labelSelectors:
      app: backend
  duration: "60s"
  scheduler:
    cron: "@every 24h"