apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: monitoring
data:
  alert-rules.yml: |
    groups:
    - name: todoapp-alerts
      rules:
      - alert: HighErrorRate
        expr: sum(rate(http_requests_total{status_code=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) > 0.05
        for: 1m
        labels:
          severity: critical
        annotations:
          title: High Error Rate
          description: Error rate is above 5% for more than 1 minute (current value = {{ $value | humanizePercentage }})
      
      - alert: SlowResponses
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          title: Slow Response Times
          description: 95th percentile of request durations is above 2 seconds for more than 5 minutes
      
      - alert: HighCPUUsage
        expr: sum(rate(container_cpu_usage_seconds_total{namespace="todoapp"}[5m])) by (pod) / sum(container_spec_cpu_quota{namespace="todoapp"} / container_spec_cpu_period{namespace="todoapp"}) by (pod) > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          title: High CPU Usage
          description: Pod {{ $labels.pod }} CPU usage is above 80% for more than 5 minutes
      
      - alert: HighMemoryUsage
        expr: sum(container_memory_usage_bytes{namespace="todoapp"}) by (pod) / sum(container_spec_memory_limit_bytes{namespace="todoapp"}) by (pod) > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          title: High Memory Usage
          description: Pod {{ $labels.pod }} memory usage is above 80% for more than 5 minutes