apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: todoapp
type: Opaque
data:
  username: cG9zdGdyZXM=  # postgres (base64 encoded)
  password: ${DB_PASSWORD_BASE64}  # буде замінено під час розгортання